export const IMG_CDN_URL = "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/" ; 

export const Fetch_Menu_URL = "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=22.7195687&lng=75.8577258&restaurantId=" ;

const restrauntlist = [
    {
      type : "restaurant" , 
      data : {
          name: "Burgur King",
          cloudinaryImageId:"si6nqgkhy2o7gsvf69ap",
          cuisines: ["Burger", "Americans"],
          avgRating: "4.2",
      }
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "255171",
        name: "Biryani On Wheels",
        uuid: "74af1d0b-5ea5-48c3-a033-0752446cffa2",
        city: "18",
        area: "Vijay Nagar",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "si6nqgkhy2o7gsvf69ap",
        cuisines: [
          "Biryani",
          "Mughlai",
          "Hyderabadi",
          "Lucknowi",
          "Kerala",
          "Goan",
          "Indian",
          "Persian",
          "Home Food",
        ],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        slaString: "23 MINS",
        lastMileTravel: 7.599999904632568,
        slugs: {
          restaurant: "indore-biryani-house-vijay-nagar-vijay-nagar",
          city: "indore",
        },
        cityState: "18",
        address: "220 EB Scheme No 94 Zakir Hotel Vijay Nagar",
        locality: "94th Scheme",
        parentId: 46908,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 8200,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 8200,
          message: "",
          title: "Delivery Charge",
          amount: "8200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7094235~p=1~eid=00000188-d547-dee6-019c-f63400730158~srvts=1687205437158",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹100 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "255171",
          deliveryTime: 23,
          minDeliveryTime: 23,
          maxDeliveryTime: 23,
          lastMileTravel: 7.599999904632568,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.7",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "70369",
        name: "Saify Hotel",
        uuid: "c000c6ef-e59b-46ce-9b1f-3e7e75b259fb",
        city: "18",
        area: "Siyaganj",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "qrgq4mxvuy2pz3t1wui2",
        cuisines: ["North Indian", "Mughlai", "Biryani"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 14,
        minDeliveryTime: 14,
        maxDeliveryTime: 14,
        slaString: "14 MINS",
        lastMileTravel: 1.100000023841858,
        slugs: {
          restaurant: "saify-hotel-sarafa-sarafa",
          city: "indore",
        },
        cityState: "18",
        address: "453, Jawahar Marg, Near Saify Hotel Square, Indore",
        locality: "Sarafa",
        parentId: 175638,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2900,
          message: "",
          title: "Delivery Charge",
          amount: "2900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "Closes soon",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.1 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "70369",
          deliveryTime: 14,
          minDeliveryTime: 14,
          maxDeliveryTime: 14,
          lastMileTravel: 1.100000023841858,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.8",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "667764",
        name: "Burger Farm",
        uuid: "790387df-16a9-4141-bf6d-25ab780be0be",
        city: "18",
        area: "Bhawar Kuan",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "5cba4ff16c5feda03a4c1d780831cd7c",
        cuisines: ["Burgers", "Beverages", "Snacks", "Desserts"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        slaString: "22 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "burger-farm-bhawar-kuan-bhawar-kuan",
          city: "indore",
        },
        cityState: "18",
        address:
          "MERRY MEALS INDIA/SHOP NO G-19 VEDA COMPLEX BHAWARKUA INDORE ,Indore,Indore,Madhya Pradesh-452001",
        locality: "Veda Complex",
        parentId: 4660,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3700,
          message: "",
          title: "Delivery Charge",
          amount: "3700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "30% OFF",
          subHeader: "UPTO ₹75",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "667764",
          deliveryTime: 22,
          minDeliveryTime: 22,
          maxDeliveryTime: 22,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "541135",
        name: "Midnight Cravings",
        uuid: "f37cd1f1-d77a-45bc-a983-b7ce93d5e7db",
        city: "18",
        area: "New Palasia",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "l1zjaqohmylrmp7jim3c",
        cuisines: ["Chinese", "Snacks", "Indian", "North Indian"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        slaString: "34 MINS",
        lastMileTravel: 4.5,
        slugs: {
          restaurant: "midnight-cravings-new-palasia-new-palasia",
          city: "indore",
        },
        cityState: "18",
        address: "8, AB Rd, New Palasia, Indore, Madhya Pradesh 452018, India",
        locality: "AB Road",
        parentId: 135948,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4500,
          message: "",
          title: "Delivery Charge",
          amount: "4500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7089671~p=4~eid=00000188-d547-dee6-019c-f63500730452~srvts=1687205437158",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "ABOVE ₹600",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "541135",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          lastMileTravel: 4.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.5",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
  ];

export {restrauntlist} ; 